### ISSUE TITLE
Compilation Error

### ISSUE THREAD

**Issue by adilahmad17** [cocoppang/ShieldStore#1]
Hey,

I get this error when I try to compile your source using the provided instructions.

``/linux-sgx/sdk/gperftools/gperftools-2.5/src/tcmalloc.cc:567: undefined reference to `operator delete(void*, unsigned long)'``

I am using the Linux SDK v1.8 linked in your readme.

Can you please let me know what this issue could be about?

Thanks!
Adil

**Comment by cocoppang** [comment]
Hi Adil,

I'm sorry that I didn't mention the building environment in the README.

In Ubuntu 16.04, you should use the rebuilt version of tcmalloc library from [here](https://01.org/intel-softwareguard-extensions/downloads/intel-sgx-linux-1.8-release)

If you use this rebuilt version of tcmalloc, you can run the code without such errors.

PS. Since I have updated revised version of ShieldStore, please use the revised version.

Thanks!
Taehoon Kim

**Comment by adilahmad17** [comment]
Oh, thanks a lot for pointing that out!

-Adil
