### ISSUE TITLE
Security Issue

### ISSUE THREAD

**Issue by mbailleu** [cocoppang/ShieldStore#2]
Hi,

I think you have a time of check to time of use bug.

in ```enclave_append``` and ```enclave_set``` you verify the existing integrity of the hash bin, before you update the list. And than you recalculate a new mac for the bin, with the changed list.

An attacker could insert or delete entries between the check and the recalculation of the hash.

Please correct me if I am wrong.

Thanks,
Maurice

**Comment by cocoppang** [comment]
Hi Maurice,

Yes, ShieldStore's policy is that checking the security (integrity & confidentiality) of data when we fetch the data from untrusted memory and supporting encryption and hash generation of data when we put the data into untrusted memory.

All the checking and recalculation of the hash are operated in an enclave which is a trusted execution environment.

Since we assume that enclave is protected by Intel SGX supports from attackers, the attack you describe doesn't affect the security of ShieldStore.

Thanks,
Taehoon Kim

**Comment by mbailleu** [comment]
I think, the bug is still present.

In ```enclave_set``` ShieldStore looks if the Key is already in the KV store at line 85. If the key is already in the store it test in line 96 if the current entry is correct (in the sense of integrity), in line 103 the bin is check for integrity violation. After that the new KV pair is inserted in line 128. And after this the MAC for the hash bin is recalculated in line 130. If I see it correctly, an attacker could insert or delete KV pairs between line 103 and line 130 in host memory. As the recalculation doesn't check if the old KV pairs are still correct. And since ShieldStore tries to protect against the OS this is not hard to time as the OS can trap all memory accesses to the host memory and deschedule the enclave accordingly.
And if I see it correctly, the problem also persists in the case that the key does not exists in the bin, as then the integrity check does not happen at all.

The same problem is present in ```enclave_append```.

However, I am happy to be wrong. Do you do some checks I do not see? Or is there a reason why this cannot happen?

Thanks,
Maurice

**Comment by cocoppang** [comment]
Hi Maurice,

Thank you for pointing out the problem :)

Yes, because the key-value entry stored in untrusted memory can be modified by attackers after verification, ShieldStore can "set" the data entry with wrong information.
I think that the naive solution is that simply copying all the fields of data entry in the enclave and verifying & operating the "set" operation with the verified data entry. In that case, at the "set" operation, ShieldStore overwrites correct key-value entries instead of the maliciously modified key-value entry.  Even if the attacker modifies a key-value entry in the untrusted memory at that moment, ShieldStore will operate correctly.
Does it make sense? :) 

Thanks,
Taehoon Kim

**Comment by mbailleu** [comment]
I am not sure what you are proposing. Do you want to copy the bin completely (or by streaming) into the enclave and recalculate/verify all hashes?

I think an easier/faster solution is to calculate the old hash in parallel to the new one. And verify that the old hash is still correct and then swap a pointer.

In other words ```enclave_verify_tree_root``` and ```enclave_rebuild_tree_root``` have to be done at the same time (with the same load instructions (at least from host memory)). This even could speed up your implementation, as you only have to go over the list once.

Thanks,
Maurice

**Comment by cocoppang** [comment]
Oh, I misunderstood the problem.

Thank you for proposing a nice solution. 
As you mentioned, tree verification and rebuilding should be done with the same tree nodes except only the updated hash value.
I will check the current implementation and fix this issue.

Thanks,
Taehoon Kim
